### ISSUE TITLE
I'm always on time...

### ISSUE THREAD

**Issue by denricoNBHS** [NBHS-STEM/stem-attendance#5]
# ...said no student ever.

attendance.py needs to be able to handle late students. Add code that allows teachers to decide when students are to be marked late.
- [ ] Add an option for teachers to press L to begin marking students late
- [ ] When a student is late, it should be recorded in the filing system you've chosen

@NBHS-STEM/intro-engineering

**Comment by denricoNBHS** [comment]
I feel like you can work on the first part of this issue - it should be similar to how you solved the infinite loop. You'll need to resolve issue #3 before deciding how to record the lates.
:necktie:

**Comment by stapia25** [comment]
lets bring back the chat :+1:

**Comment by swimmerboi2001** [comment]
The one on the left was Enrico's

**Comment by andrewfuentes** [comment]
yeah man :100:

**Comment by jadesus** [comment]
:gem: :100:

**Comment by andrewfuentes** [comment]
:runner: :100:

**Comment by andrewfuentes** [comment]
:peach:
